### ISSUE TITLE
JS/TS diagnostics not working

### ISSUE THREAD

**Issue by refrainsclub** [zed-industries/community#2256] opened 2023-11-11 09:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I cannot see JavaScript/TypeScript diagnostics (errors and warnings). For example, when I type invalid syntax there are no red squiggly lines. Nor are there errors under the project diagnostics.

Autocomplete works. If I type `document.get`, it will give options such as `getElementById`, `getElementsByClassName`. So I assume the LSP is working besides for the diagnostics.

Steps to produce:
1. Install latest Zed release on macOS
2. Create a JavaScript file
3. Write invalid code
4. Check if there are any errors

I have tried:
1. Using the latest preview version of Zed
2. Deleting node_modules, package.json and related files from my home directory
3. Cloning relevant LSPs into the Zed application support folder
4. Deleting ~/Library/Application Support/Zed
5. Reinstalling Zed
6. Upgrading the NodeJS install using nvm
7. Checking other languages (Rust diagnostics do work)
8. Disabling features such as Copilot

### Environment

Zed: v0.111.6 (stable)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="367" alt="Screenshot 2023-11-11 at 9 51 50 PM" src="https://github.com/zed-industries/community/assets/36752154/fe19e9f3-6817-48dc-9b3c-eabae264bfd3">
<img width="361" alt="Screenshot 2023-11-11 at 9 52 01 PM" src="https://github.com/zed-industries/community/assets/36752154/061ce5e2-54de-4a88-852f-2e652459867a">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/13325014/Zed.log)

**Comment by kwando** [comment] 2023-11-13 22:31
I'm using 0.112.3 preview. The JS/TS language server has been super unreliable lately, completely unusable. :/

**Comment by kwando** [comment] 2023-11-13 22:44
If you type something in a project with type errors the LSP just spins... over 29K RPC messages now while not doing anything, still just looping... zed  using 700% CPU, 21GB of RAM.

**Comment by SomeoneToIgnore** [comment] 2023-11-14 08:04
Is there a project we can use to reproduce this?

**Comment by gawlk** [comment] 2023-11-20 09:27
Still broken in `0.112.3`

**Comment by JosephTLyons** [comment] 2023-11-20 16:01
Hey all, we will be talking about this issue in today's all-hands meeting.  I will update with what comes of it.

**Comment by chrisbrown-io** [comment] 2023-11-22 15:32
Looks like a fix _might_ be incoming in `0.113.0`?

Just spotted this in the [Preview Releases](https://zed.dev/releases/preview)

> Bug Fixes
> Fixed a few issues preventing Javascript/Typescript language server from working with latest upstream changes.

**Comment by matthewmorek** [comment] 2023-11-24 11:13
For me diagnostics or any sort of LSP support stopped working just this week, likely after an auto-update of Zed. I tried downgrading Zed, redownloading LSP packages, wiping the app clean, changing configuration, reverting to defaults. Nothing.

I can still LSP spitting out a ton of RPC messages, some with issues or hints related to my code, but Zed does not report anything in the UI, or for affected documents.

I have to switch back to VS Code, as otherwise I can't get any work done reliably, while Zed for me worked flawlessly for a few months now...

**Comment by matthewmorek** [comment] 2023-11-29 22:15
I have one test repo which is TypeScript heavy and should be a good testing ground. Will try to replicate over the weekend, using default and custom configs alike.

**Comment by Aeolun** [comment] 2023-12-01 01:40
It looks like this is fixed in the latest preview release?

**Comment by refrainsclub** [comment] 2023-12-01 10:26
Appears to be fixed in the latest version, thanks so much.

**Comment by matthewmorek** [comment] 2023-12-01 10:46
I'll check the preview release and report back if it has worked.

**Comment by SomeoneToIgnore** [comment] 2023-12-06 07:38
So we have a few reports that it works, hence closing this.

**Closed by SomeoneToIgnore** 2023-12-06 07:38 UTC
Labels: defect, typescript, javascript, language
