### ISSUE TITLE
zed is not opening

### ISSUE THREAD

**Issue by victororlyk** [zed-industries/community#1229] opened 2023-03-20 06:18 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps:
cmd + space type zed and hit enter
Result:
mac tells that it is open
and I would like to see the window go to the front
but nothing happens

### Environment

mac

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/33072590/226261810-7b301544-288f-4405-b521-2d37301977a7.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jansol** [comment] 2023-03-20 11:08
This is a duplicate of #1148 :

Zed opens, like the dock indicator suggests and the menu bar changes to show the menus of Zed whenever the app is focused. It just does not open a window automatically, you have to click on File > New Window to get one. (or use the cmd-shift-N shortcut for it)

Do people just never look at the global menu bar? 😄

**Comment by jansol** [comment] 2023-03-20 18:23
I agree, the current behavior is not desirable.

So please go give the older issue a :+1: so we can keep the votes for one issue in one place.

**Comment by JosephTLyons** [comment] 2023-03-21 14:41
Closing this in favor of #1148.

**Closed** 2023-03-23 14:18 UTC
Labels: defect
