### ISSUE TITLE
Drag'n'drop files

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1992] opened 2023-09-08 19:48 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Allow any file to be dragged and dropped into current work window

**Comment by JosephTLyons** [comment] 2023-09-08 20:12
Hey @krstp ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/1317

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2023-09-08 20:12 UTC
Labels: enhancement, triage, admin read

**Comment by krstp** [comment] 2023-09-08 23:29
I knew it, it was somewhere there. Thanks!
