### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by carlca** [zed-industries/community#1727] opened 2023-07-03 13:12 UTC
### Check for existing issues

- [X] Completed

### Language

Scala 

### Tree Sitter parser link

https://github.com/tree-sitter/tree-sitter-scala

### Language server link

https://github.com/scalameta/metals

**Comment by aexvir** [comment] 2023-07-03 19:25
this seems to be a duplicate of https://github.com/zed-industries/community/issues/299 please upvote that issue to show interest 🙂 

closing this one

**Closed by aexvir** 2023-07-03 19:25 UTC
Labels: enhancement, language, potential plugin
