### ISSUE TITLE
Add a single file to project

### ISSUE THREAD

**Issue by sethherr** [zed-industries/community#1881] opened 2023-08-03 19:28 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I frequently want to have something open in my editor that isn't in the project I'm working on.

In Sublime or VSCode, I can open up a file and then drag that file tab into another workspace. 

I want to be able to do something similar in zed. Adding a single file to the workspace seems like the most intuitive way to provide that functionality.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/community/assets/1235441/b44bb715-4a8d-4042-807e-4c4542d2c049

**Comment by JosephTLyons** [comment] 2023-08-18 12:31
Hey <user>,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/493

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2023-08-18 12:31 UTC
Labels: enhancement, project panel

**Comment by sethherr** [comment] 2023-08-18 13:15
Ooh, yeah - that's a better solution.
