### ISSUE TITLE
Using Nushell, automatic Python env activation print venv source command in terminal as input

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/community#2103] opened 2023-09-30 20:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using automatic Python env activation with Zsh shell in Terminal, it works perfectly, the venv source command is automatically executed and the terminal prompt input is clear and empty as expected.
With Nushell the venv is activated but the terminal prompt input is filled with the venv source command.

### Environment

Zed: v0.106.2 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1512" alt="Capture d’écran 2023-09-30 à 22 04 27" src="https://github.com/zed-industries/community/assets/24520681/ba9c2918-c1ff-4c8b-8fde-2dbb4837acaa">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2023-10-02 03:19
This is an interesting bug.  Looks like things are also correct in fish. Not sure why that line is being duplicated into the prompt of nushell.

**Comment by JosephTLyons** [comment] 2023-10-02 03:32
Ah, here's tbe problem.

When you run the `source` command in nu, an error comes up on nushell's side:

```zsh
/Users/josephlyons/Projects/Work/feedback_commander〉source /Users/josephlyons/Projects/Work/feedback_commander/.venv/bin/activate
Error: nu::parser::shell_andand

  × The '&&' operator is not supported in Nushell
    ╭─[/Users/josephlyons/Projects/Work/feedback_commander/.venv/bin/activate:48:1]
 48 │ VIRTUAL_ENV='/Users/josephlyons/Projects/Work/feedback_commander/.venv'
 49 │ if ([ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ]) && $(command -v cygpath &> /dev/null) ; then
    ·                                                         ─┬
    ·                                                          ╰── instead of '&&', use ';' or 'and'
 50 │     VIRTUAL_ENV=$(cygpath -u "$VIRTUAL_ENV")
    ╰────
  help: use ';' instead of the shell '&&', or 'and' instead of the boolean '&&'
```

It looks like the `activate.sh` script is using operators not supported by nushell.  What's interesting is I'm looking in the `.venv/bin` directory and I found an `activate.nu` file.  This is newer! So I switched the source command:

```zsh
/Users/josephlyons/Projects/Work/feedback_commander〉source /Users/josephlyons/Projects/Work/feedback_commander/.venv/bin/activate.nu
Error: nu::parser::unexpected_keyword

  × Statement used in pipeline.
    ╭─[/Users/josephlyons/Projects/Work/feedback_commander/.venv/bin/activate.nu:95:1]
 95 │ export alias pydoc = python -m pydoc
 96 │ export alias deactivate = overlay hide activate
    ·                           ───┬───
    ·                              ╰── not allowed in pipeline
    ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
```

And this one is also busted.  We will add an option to the terminal settings to allow for launching `activate.nu`, but it will be busted until they fix it on their side.

**Comment by JosephTLyons** [comment] 2023-10-02 03:53
I just merged a PR to add a `nushell` option to the `terminal.detect_venv.on.activate_script` setting, to run the `activate.nu` file, but as stated above, it will still be busted until someone fixes it.  I'm not sure if the issue is on nushell's side or those who wrote the `activate.nu` file. I'll close this issue out, but feel free to open any new issues if it still doesn't work after its fixed upstream.

**Closed by JosephTLyons** 2023-10-02 03:53 UTC
Labels: defect, terminal, python
