### ISSUE TITLE
File tree inconsistent with disk after case-sensitive rename

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/community#1439] opened 2023-04-13 21:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I renamed a file on disk from `App.tsx` to `app.tsx` before opening Zed. It opened and worked fine.

Doing something like this causes issues with git, because it doesn't usually care about case. So I ran `git mv App.tsx app.tsx`, to have git register the change.

After this, Zed's File Tree sidebar displayed _two_ files, both `App.tsx` _and_ `app.tsx` (when in reality only the lower-case version existed on disk). Trusting the sidebar and thinking I had two files, I asked Zed to delete the upper-case file. It deleted the (one) lower-case file and left me with nothing.

### Environment

Zed: v0.81.1 (stable)
OS: macOS 13.3.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by adamsoutar** [comment] 2023-04-22 22:22
Ran into this again with *much* simpler repro steps, and I'm starting to think this is a fairly common issue with renaming anything that involves only changing the case of letters.

Here, all I did was change `Favicon.ico` to `favicon.ico` using Finder outside of Zed. It's broken the project panel again. 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/26578100/233809233-20260a14-4531-4f0f-a694-5877c10a79e9.png">

**Comment by locustbaby** [comment] 2023-08-01 02:58
Related issues +1, Can't change letter case, when I change it to uppercase and press ENTER this doesn't work!

https://github.com/zed-industries/community/assets/21237232/df1d6baa-828c-4e19-8c32-52dabb8f2196

**Comment by CurbaiCode** [comment] 2023-08-17 14:19
This appears to be a duplicate of #525.

**Comment by JosephTLyons** [comment] 2023-08-18 20:19
Thanks for the report @adamsoutar, and I do think this is a duplicate of #525, so I'll close this one in favor of that one.

**Closed by JosephTLyons** 2023-08-18 20:19 UTC
Labels: defect, macOS, project panel
