### ISSUE TITLE
Unable to remove specific keybindings

### ISSUE THREAD

**Issue by SogoCZE** [zed-industries/community#772] opened 2022-12-09 04:09 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that you cannot remove specific keybindings. If you remove a keybinding from the custom keybinding config, it will fall back to the default one. The problem I have is that in my Czech keyboard layout, I type `{ `with `alt-b` and `}` with `alt-n`, and there are default keybindings for these combinations, so I cannot type `{` in Zed right now.

To solve this, I would suggest either:

1. Allowing to pass an empty string, `false`, or `null` as a keybinding command, so that these keybinds wouldn't block the default OS behavior.
2. Don't fall back to default keybindings.

### Environment

Zed 0.66.0 – /Applications/Zed.app
macOS 13.0
architecture arm64

**Comment by tom2strobl** [comment] 2023-02-23 13:42
On mac/german using `alt-v` prints this character: √ which I personally like to use in quick notes to mark as something completed. Zed currently has
```
"alt-v": ["editor::MovePageUp", { "center_cursor": true }],
```
which I'd like to deactivate.

**Comment by probablykasper** [comment] 2023-03-14 23:19
`Alt+<character>` should probably not be used for any shortcuts by default. `Alt+V` is like `Shift+V`, it's already used for typing characters.

**Comment by DanielBreiner** [comment] 2023-03-17 13:21
Any update on this? It's been the top-ranked defect issue for quite some time now and makes the software unusable for people which use certain keyboard layouts.

**Comment by DanielBreiner** [comment] 2023-05-13 15:13
After half a year, Zed is still unusable for a large number of europeans developers :( . Could we at least get a response from the devs that they are aware of this issue and some estimate on when this might get fixed -- or at least some statement about its priority?

**Comment by SogoCZE** [comment] 2023-05-13 21:09
@JosephTLyons

**Comment by JosephTLyons** [comment] 2023-05-15 17:07
Hey all, I brought this up with the team today in our meeting.  It seems like everyone agreed that this is not great, so sorry for dropping the ball here.  I'll update the issue when I know where the fix might land.

**Comment by JosephTLyons** [comment] 2023-07-05 18:46
Closing this issue as this should be availabe in 0.94.x.

**Closed by JosephTLyons** 2023-07-05 18:46 UTC
Labels: defect, settings, keymap / key binding

**Comment by TomPlanche** [comment] 2023-12-18 08:50
@JosephTLyons Hi, the problem is still relevant (#1540).
