### ISSUE TITLE
Help Needed in configuring Zed

### ISSUE THREAD

**Issue by uzaxirr** [zed-industries/community#1288] opened 2023-03-23 19:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've brought a new MacBook and installed zed on it. Now since then I guess I'm not able to access any of the features.
My Code Suggestions aren't working, Project-wide diagnostics, Buffer diagnostics and all are also not working. Can someone point out what wrong am I doing. I primarily code in Python.

Here are my configs files.

`settings.json`

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
    "theme": "Andromeda",
    "buffer_font_size": 15,
    "autosave": "on_focus_change",
    "language_overrides": {
        "Python": {
            "format_on_save": {
                "external": {
                    "command": "black",
                    "arguments": [
                        "-"
                    ]
                }
            }
        }
    }
}
```

Also as you can see I have autosave turned on but still I have to manually save for some reason I don't know why.

`pyrightconfig.json`
```json
{
    "venvPath": "../../Library/Caches/pypoetry/virtualenvs/",
    "venv": "westeros-QZJB6mVN-py3.8"
}

```

`/Users/uzaxirr/work/westeros` is my working directory for project and `/Users/uzaxirr/Library/Caches/pypoetry/virtualenvs/westeros-QZJB6mVN-py3.8` is where my virtual env resides
<img width="808" alt="Screenshot 2023-03-24 at 12 45 21 AM" src="https://user-images.githubusercontent.com/72073401/227323848-259fe77b-0c4f-4112-9046-d8f5e1cea426.png">

### Environment

Zed: v0.78.1 (stable)
OS: macOS 13.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by WindSoilder** [comment] 2023-03-23 22:40
I guess you're not downloading language-server successfully, you can check logs to see if there are any error messages about it

**Comment by uzaxirr** [comment] 2023-03-23 22:41
> I guess you're not downloading language-server successfully, you can check logs to see if there are any error messages about it

![Screenshot 2023-03-24 at 4 11 11 AM](https://user-images.githubusercontent.com/72073401/227380570-a459351e-8377-4635-a48f-3774aad0ff08.png)
I'm getting this error

**Comment by WindSoilder** [comment] 2023-03-23 22:47
Can you go into `~/Library/Application Support/Zed/languages` directory and see if there is a directory called `pyright`?  If it's not exists, then the language server is not downloaded successfully

**Comment by WindSoilder** [comment] 2023-03-23 22:48
![图片](https://user-images.githubusercontent.com/22256154/227381542-61511672-0f3d-4b24-b08d-4e278abd6f49.png)
Here is my pyright information

**Comment by uzaxirr** [comment] 2023-03-23 23:10
<img width="874" alt="Screenshot 2023-03-24 at 4 39 38 AM" src="https://user-images.githubusercontent.com/72073401/227384303-904f1e25-4bec-4af9-b1c9-78cd92558aa0.png">

@WindSoilder Yes I do have a `pyright` directory but it's empty though!

**Comment by WindSoilder** [comment] 2023-03-23 23:48
Not really sure are `json-language-server`, `yaml-language-server`, `clangd` empty?  If just `pyright` is empty, you can try to delete the directory and restart zed again.

It's how I'm working around it when I get similar issue.

**Comment by fdionisi** [comment] 2023-03-24 05:00
Hey @uzaxirr, it looks like you are [not alone](https://github.com/zed-industries/community/issues/1265#issuecomment-1481410947). If you believe the problem is the same, I'd suggest moving the conversation to the other issue and closing this one (since the other is followed by the core team already).

**Comment by JosephTLyons** [comment] 2023-03-24 05:05
Hey @uzaxirr, what version of node are you using?  Regardless, we are working to get these resolved.

**Comment by uzaxirr** [comment] 2023-03-24 05:15
> Hey @uzaxirr, what version of node are you using? Regardless, we are working to get these resolved.

I think I got the issue, As I've mentioned that it's a new Mac I haven't installed node in it yet. I'm assuming that it is a dependency and which causes language server fails to download.

<img width="704" alt="Screenshot 2023-03-24 at 10 35 57 AM" src="https://user-images.githubusercontent.com/72073401/227429934-f95b8f5f-7fd5-4978-952f-7f4457fb90a5.png">


Just installed node and restarted zed, not my completions and stuff is working and language server is also downloaded.


Now can you also point out why my autosave isn't working?

**Comment by JosephTLyons** [comment] 2023-03-27 19:42
Since this is a duplicate of #1265, let's go ahead and close this out to keep everything in one spot.  As I mentioned in the other issue, fixes for npm-related language server issues should be landing soon.

**Closed by JosephTLyons** 2023-03-27 19:42 UTC
Labels: defect, triage
