### ISSUE TITLE
Color code recently updated files

### ISSUE THREAD

**Issue by SilentGlasses** [zed-industries/community#1321] opened 2023-03-30 01:54 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Would be nice to be able to tell what files were updated by making them show a different color like it does for Pulsar.  Example:

green = new file(s) or dir(s)
yellow = updated file(s) or dir(s)

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot](https://user-images.githubusercontent.com/22822565/228707899-6228c2e5-f733-415c-b8f1-488d284ce181.png)

**Comment by PineappleRind** [comment] 2023-03-30 17:47
Related (using Git to determine file status): #29

**Comment by JosephTLyons** [comment] 2023-03-30 19:21
ah yeah, this would be a duplicate of #29 - nice catch @PineappleRind.  Will close this as a duplicate.  Feel free to upvote the other issue.

**Closed by JosephTLyons** 2023-03-30 19:21 UTC
Labels: enhancement, project panel
