### ISSUE TITLE
Folding an entire file in vim mode triggers a crash.

### ISSUE THREAD

**Issue by whereistejas** [zed-industries/community#2071] opened 2023-09-21 13:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
Steps to reproduce crash:
1. In vim mode, open a file.
2. Select everything in visual mode.
3. Use `zc` to fold everything. 

This triggers a crash.

I'm also using `rust-analyzer` and LSP. I don't know if the crash is resulting from some funny interaction between zed and `rust-analyzer`.

### Environment

Zed: v0.104.4 (stable)
OS: macOS 13.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[zed-log.txt](https://github.com/zed-industries/community/files/12685352/zed-log.txt)

**Comment by ConradIrwin** [comment] 2023-09-26 15:12
Thanks for reporting this!

I can reproduce this on v0.103.x (and I put a fix in v0.104.4), but I see your report is on v0.104.4 – has it happened since you upgraded?

If so, are there any more details you can share about the reproduction? (specific file type / content?)

**Comment by whereistejas** [comment] 2023-09-26 18:05
I mostly got this crash on really huge files. I only used zed with `rust` or `scss` files. So those are the only examples I have.

**Comment by ConradIrwin** [comment] 2023-09-27 01:55
Makes sense, thanks! Please let me know if it happens again - I do think
it was likely the bug I fixed in 104

**Closed** 2023-10-06 01:32 UTC
Labels: defect, panic / crash, vim
