### ISSUE TITLE
Language server error: TypeScript

### ISSUE THREAD

**Issue by Alexigbokwe** [zed-industries/community#1450] opened 2023-04-17 22:40 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

Language server error: TypeScript

failed to run npm info

Caused by:
    Permission denied (os error 13)

### Environment

Zed: v0.81.1 (stable)
OS: macOS 13.3.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by hovsater** [comment] 2023-04-18 14:29
It can be caused by a bad installation of either Node or the TypeScript language server. Could you please try the following steps:

1. Quit Zed completely.
2. In a terminal of your choice run:
```console
$ rm -rf ~/Library/Application\ Support/Zed/node
$ rm -rf ~/Library/Application\ Support/Zed/languages/typescript-language-server
```
3. Open Zed again.

Is the issue resolved?

**Comment by Alexigbokwe** [comment] 2023-04-18 15:01
Yes thanks @hovsater

**Comment by hovsater** [comment] 2023-04-18 15:31
Great! Feel free to close the issue as well. 🙂

**Closed** 2023-04-18 15:52 UTC
Labels: defect, triage
