### ISSUE TITLE
windows support 

### ISSUE THREAD

**Issue by Ashaduzzaman10** [zed-industries/community#1319] opened 2023-03-29 22:07 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

i am very happy with this ide in mac but when i use windows i cannot run this ide on windows . its only for mac .
its a humble request  if possible pls make a version that support windows

**Comment by fdionisi** [comment] 2023-03-29 23:19
Hey @Ashaduzzaman10, this is a duplicate of https://github.com/zed-industries/community/issues/171 - I suggest you close your issue and 👍 the one attached.

**Comment by JosephTLyons** [comment] 2023-03-30 01:11
Will close this out as a duplicate - feel free to vote on the linked issue that @fdionisi mentioned.

**Closed by JosephTLyons** 2023-03-30 01:11 UTC
Labels: enhancement

**Comment by GitMurf** [comment] 2023-06-15 18:21
> Will close this out as a duplicate - feel free to vote on the linked issue that @fdionisi mentioned.

@JosephTLyons it does not let you "vote" in that thread because it was locked. Where can discussion happen about Windows? I understand the team priorities and direction (which is fine) but it does feel a bit off-putting the way this has been communicated and feels a bit like "hey Windows users, we don't really want to hear from you so can you please stop engaging in our GitHub repo...". Just some honest feedback.

**Comment by hovsater** [comment] 2023-06-15 18:28
@GitMurf the platform specific issues got locked because no healthy conversation was taking place, not because we're trying to silence the community. In fact, they were created for that exact purpose. For us to gather feedback from the community.

**Comment by GitMurf** [comment] 2023-06-16 19:12
@hovsater totally understand, it is just the tone of a few of the comments from the team. I'm sure it was getting annoying for you guys but the key is not letting the community feel like you are annoyed ;) What about opening up a Discussion item for people to vote and discuss Windows? It would just be nice to have a single spot to go to in order to follow discussion and updates for down the road.
