### ISSUE TITLE
Window not showing

### ISSUE THREAD

**Issue by senevr** [zed-industries/community#1286] opened 2023-03-23 15:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I downloaded Zed from https://zed.dev/download, ran the .dmg file and dragged it to the applications folder, then start the Zed application, it shows running on the dock but there is no window for me to see? Like, nothing happens..?

### Environment

MacBook Air M1
macOS Ventura 13.2.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://imgur.com/a/HBQpk4h

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by krlv** [comment] 2023-03-24 22:01
I'm having the same issue:

### Steps to reproduce
1. Install the latest Zed release from .dmg file
2. Open Zed app
3. No window is showing on a Zed start up (not even a "getting started" window with theme and hotkey configs)

### Environment
macOS Monterey 12.5
Apple M1 Max

### Zed Version
Zed 0.78.1 (https://zed.dev/api/releases/stable/0.78.1/Zed.dmg)

@senevr here's how you can still work with Zed:
https://imgur.com/a/Ospk4iE
1. Open Zed
2. In menu bar click "File" > "New Window" (or "File" > "Open" to open an existing file)
3. You'll be able to see an actual Zed window!

I don't know if this behavior is by design (I hope not 😅 ) but at least you will be able to try Zed.

**Comment by iamnbutler** [comment] 2023-03-29 17:10
Closing in favor of #1148

**Closed by iamnbutler** 2023-03-29 17:10 UTC
Labels: defect, workspace
