### ISSUE TITLE
elixir-ls language server not working

### ISSUE THREAD

**Issue by posthardcode** [zed-industries/community#1526] opened 2023-05-10 15:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Completely removed `languages` with `rm -Rf ~/Library/Application\ Support/Zed/languages`
- Started Zed
- elixir-ls seems to have been installed without errors
- On trying to format an `.exs` file and opening the log, I see this error message `2023-05-10T14:57:45 [ERROR] lsp request failed`
- Opening language server logs shows `No server selected`

### Environment

Zed: v0.84.5 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2023-05-10T15:00:29 [ERROR] lsp request failed

Caused by:
    Invalid Request
2023-05-10T15:00:29 [INFO] unhandled notification window/logMessage:
{
  "message": "Unmatched request: %{\"id\" => 23, \"jsonrpc\" => \"2.0\", \"method\" => \"textDocument/typeDefinition\", \"params\" => %{\"position\" => %{\"character\" => 37, \"line\" => 19}, \"textDocument\" => %{\"uri\" => \"file:///REDACTED\"}}}",
  "type": 2
}
```

**Comment by hovsater** [comment] 2023-05-11 10:59
There are some requests that may fail without the language server actually having a problem. For instance, unsupported requests. I don't think there's a problem with `elixir-ls` in this case.

> Opening language server logs shows `No server selected`

This is just a somewhat unfortunate UI on our part. The text is clickable and will reveal a dropdown where you can select the language server you're interested in seeing logs from.

Have you been able to verify that your language server indeed isn't working?

**Comment by hovsater** [comment] 2023-05-11 12:16
No worries. 🙂 

> But while we're at it (I can also open a specific issue for it, if you prefer), I'm struggling to find the right config to run mix format on save.

So a few things to note here. By default, the language server will do formatting for you (there's no need to configure anything). If you prefer to use `mix format` directly instead, you'd have to configure an external formatter. Note, an external formatter has nothing to do with the language server.

**Comment by noozo** [comment] 2023-05-18 10:08
Adding an update regarding elixir 1.14.4 and Erlang 26.0:

```
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "Started ElixirLS v0.14.6",
  "type": 3
}
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "Running in /Users/void/Development/web",
  "type": 3
}
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "ElixirLS built with elixir \"1.12.3\" on OTP \"22\"",
  "type": 3
}
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "Running on elixir \"1.14.4 (compiled with Erlang/OTP 26)\" on OTP \"26\"",
  "type": 3
}
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "Protocols are not consolidated",
  "type": 3
}
2023-05-18T10:07:28 [INFO] unhandled notification window/logMessage:
{
  "message": "Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.",
  "type": 3
}
```

**Comment by maxbrunsfeld** [comment] 2023-06-08 20:19
I've been testing Elixir-LS in Zed, using the `phoenix` repo, and it seems to work alright for me; I get jump-to-definition, hover information, formatting, and auto-complete.

I also get the same messages as @noozo mentioned - "Code navigation to Elixir modules disabled". I believe it's because I installed `elixir` via Homebrew, and don't have the source code on my machine.

In Zed 0.91, there will be some minor improvements based on things I saw in this testing:
* Better `language server logs` view, which lets you view the messages reported by the server via `logMessage`
* Fixed some spurious error messages coming out of `elixir-ls` due to Zed not noticing that certain LSP features were not supported.

I'm going to close this out for now. Let me know if you're not able to get Elixir-LS to work in Zed, and you believe the issue is on Zed's side.

**Closed by maxbrunsfeld** 2023-06-08 20:19 UTC
Labels: defect, elixir, language server
