### ISSUE TITLE
file finder no longer proactively indexes my repo

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/community#1758] opened 2023-07-13 10:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add folder to project. Open file finder (cmd+p) and type. Only top-level files from the added folder are shown. If I unfold a folder in the project panel, the top-level files of that folder are also indexed.

In earlier versions, all files from the project could be opened immediately from the file finder.

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by aexvir** [comment] 2023-07-15 09:02
I can't reproduce this, I'm getting results from all levels of the file hierarchy, not just top levels, and I don't need to expand anything in the project panel, are you experiencing this same issue when working with other directories?

**Comment by mikayla-maki** [comment] 2023-07-16 06:17
This might happen if @hferreiro has a folder full of symlinks

**Comment by hferreiro** [comment] 2023-07-17 13:12
This happens with the chromium repo (definitely not the standard repo in terms of size). I removed `~/Library/Application Support/Zed` and observed the behavior.
After adding the project folder, it starts running at 100% CPU for hours. When trying to search for a file, in the first 15-30 min. I cannot find most of them. Looking at the results, and how they change, it appears this time is used to build an index.
Every time I close, and open zed again, this indexing starts from scratch.

IIRC, the previous behavior was to return results immediately, as happens with VSCode for example, which uses `ripgrep` under the hood.

**Comment by aexvir** [comment] 2023-07-17 13:41
aha, I see, ok so this will have to be looked into, thanks for adding more details

**Comment by hferreiro** [comment] 2023-08-07 05:30
Duplicate of #1770.

**Comment by hferreiro** [comment] 2023-08-07 12:52
I thought this was fixed together with #1770, but it's not. There's a different behavior now: I can almost instantly open folders in the project panel (which I previously couldn't), but indexing doesn't appear to work (cmd-p cannot find any file other than the ones from folders I manually expanded and the Activity Monitor doesn't show Zed doing any activity.

**Comment by hferreiro** [comment] 2023-08-07 17:08
No, I'm using chromium. Most of the code is directly checked out, then it has some subdirectories with other repos.
I'm using the latest stable version of Zed.

**Comment by maxbrunsfeld** [comment] 2023-08-07 18:12
Ok, you're using Zed 0.97.5? I can't actually reproduce the problem in the `chromium` repo. Zed previously had a lot of problems in this repo (ever since we added git status highlights in the project browser), but we shipped some performance improvements in 0.97.x, which have fixed the problems AFAICT.

When I open `chromium` in Zed 0.97.5, it's pretty responsive and file navigation works fine.

**Comment by hferreiro** [comment] 2023-08-08 11:47
I found the issue. I'm actually using brave, not chromium. The repo is setup as this: brave-browser/ is the main repo where the chromium sources are checked out at brave-browser/src/. In brave-browser/ there's an entry for src in .gitignore.

I guess Zed is looking upwards for .gitignore files? This perhaps should be avoided in general. Another thing is that the file is not monitored, so I had to restart Zed for the changes to apply.

**Comment by maxbrunsfeld** [comment] 2023-08-10 00:45
Ok, thanks for the follow-up. I'm going to close this one out, since the situation has changed significantly since it was originally opened.

Would you mind creating a new issue about the `.gitignore` thing? If I understand correctly, when the *entire* project that you're editing is a git-ignored directory within a larger repo, what we do (defer indexing your project) is not very useful or intuitive.

**Closed** 2023-08-10 00:46 UTC
Labels: defect, file finder

**Comment by hferreiro** [comment] 2023-08-10 06:10
OK. The issue about `.gitignore` had already been reported: https://github.com/zed-industries/community/issues/575.
