### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1597] opened 2023-06-01 19:09 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hmm.. after recent updates something changed. The text scrolling is slow compared to any other editor etc. Good comparison vs. sublime which is super snappy compared to current ZED release.

### Environment

Mac M2

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxbrunsfeld** [comment] 2023-06-01 20:34
Could you share a file that's slow to scroll? If not, maybe some more information about the file would help to diagnose. Are there lots of diagnostic errors, or git changes, or anything else notable about the file?

**Comment by krstp** [comment] 2023-06-01 22:01
Nothing in particular, regular Markdown file approx. 600 lines. This GIF might not fully show it without mouse/trackpad touch, but it is some kind of lack of smoothness if you can catch it. No diagnostic errors, no git changes, just standalone file.

![lorem](https://github.com/zed-industries/community/assets/4711498/7a611031-4a3c-43c0-b22b-2cb1ac3b5e87)

**Comment by Yevgnen** [comment] 2023-06-02 00:34
Experiencing the same issue. Does not compare with other editor, but the difference between the latest version and last version is pretty much noticeable.

**Comment by maxbrunsfeld** [comment] 2023-06-05 19:06
I can't reproduce this yet. If either of you get a chance, could you try to create a minimal reproduction for this (like, provide a public project that someone could open in Zed, and share a specific file where the problem happens reliably, share what your zed settings contain, if anything)?

Another data point that would be very interesting is opening the `Activity Monitor` app, selecting the `Zed` process and recording a sample (`View > Sample Process` in the application menu, or `cmd-alt-s`) and scrolling the editor while the sample is recording.

**Comment by krstp** [comment] 2023-06-07 04:38
Valid points.
- atm working on M2, not seeing the issue that much as... hardware is latest and greatest. Using magic mouse.
- the "slowness" was seen when I worked on my one-of-latest Intels... not sure though if it was magic mouse or touchpad. When I get a chance I will retest and revert on the subject.

**Comment by ForLoveOfCats** [comment] 2023-06-20 16:39
This should be fixed once we ship 0.92!

**Closed by ForLoveOfCats** 2023-06-20 16:39 UTC
Labels: defect, performance, editor
