### ISSUE TITLE
[Terminal Args] Add parameter to reuse current window

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/community#2114] opened 2023-10-05 06:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode terminal command has the `-r` option which allows to reuse current window when opening a file/directory so if you type the following from the VSCode integrated terminal, this will reuse active VSCode window to open the specified folder:

> code -r ./folder

Right now, typing `zed ./folder` in a folder from within Zed will always open `folder` in a new window: I wish there was an option to make Zed reuse current window just like in VSCode.

**Comment by JosephTLyons** [comment] 2023-10-05 18:01
Hey @warpdesign,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/1314

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2023-10-05 18:01 UTC
Labels: enhancement, cli
