### ISSUE TITLE
sytem ui support change font family

### ISSUE THREAD

**Issue by d1y** [zed-industries/community#1158] opened 2023-03-16 16:14 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Can these system UI fonts support custom fonts 😁 ?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/45585937/225682977-e48e6fd6-cba7-4c2a-b412-8d273d5c90d2.png">

**Comment by wzxu** [comment] 2023-03-17 15:40
Think this is a duplicate of #330.

**Closed** 2023-03-17 16:14 UTC
Labels: enhancement, workspace, font
