### ISSUE TITLE
While Zed is running, coreaudiod CPU usage is constantly above 15%

### ISSUE THREAD

**Issue by dlindenkreuz** [zed-industries/community#1840] opened 2023-07-28 11:46 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure why this happens, but whenever Zed is running on macOS, `coreaudiod` constantly uses more than 15% CPU (observable in Activity Monitor). As soon as I close Zed, `coreaudiod` CPU usage reliably returns to 0%.

This is reproducible every single time on my machine. Rebooting does not help. Zed causes this issue even without any open editor windows. I am not logged in and do not use the built-in call feature.

I have a hunch that this also interferes with Google Meet calls. Every once and then, I need to kill `coreaudiod` to get sound working again. I am afraid I cannot continue to use Zed because of this.

### Environment

Zed: v0.96.3 (stable)
OS: macOS 13.4.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Not applicable — no recent logs that match the time window where the issue occurs.

**Comment by jansol** [comment] 2023-07-28 12:29
Can reproduce, although not quite as drastic (coreaudiod goes from 0.5% CPU to 5.5% when launching Zed). Additionally it seems to taper out over time, going all the way back to 0.5% when Zed is open in the background but has no open windows for a prolonged time, as I only noticed afterwards that I already had a different instance running.

**Comment by dlindenkreuz** [comment] 2023-07-28 12:40
For me, CPU usage stays above 15% even after an hour of continuously running Zed. I made sure there are no other apps running that use audio. Siri / Hey Siri are both turned off (found on some other forums that this may have an effect but it seems to not alleviate the situation).

I use a M2 MacBook Air 15" (2023).

**Comment by iamnbutler** [comment] 2023-07-28 17:08
Interesting. cc @mikayla-maki, this must be starting too aggressively even if you are not in a call for some reason (I say with not a lot of knowledge of this, Mikayla should have more context.)

**Comment by iamvoidcoder** [comment] 2023-08-03 22:42
Doh, just checked and it happens to me too. Quitting Zed and coreaudiod drops to 0% in few seconds. Launching Zed and it is back to consistent ~4-5% CPU use. What on earth is going on? Doesn't seems to be playing nor recording so why the sudden Core Audio load? 🤔

**Comment by JosephTLyons** [comment] 2023-08-16 20:04
This should be fixed in v0.100.x - please reopen if the issue persists.

**Closed by JosephTLyons** 2023-08-16 20:04 UTC
Labels: defect, collaboration, audio
