### ISSUE TITLE
Option to fold in all folders in project panel

### ISSUE THREAD

**Issue by PaulvdDool** [zed-industries/community#1542] opened 2023-05-15 11:53 UTC
### Check for existing issues

- [X] Completed

### Problem description
After working for a bit, due to the auto focus in the Project Panel for the file in the active tab, the Project Panel will have multiple folders open potentially several items deep into the project tree. Some of these folders can contain a lot of files. It's easy to loose oversight and it becomes difficult to navigate via the Project Panel.

### Feature description
An option to close all folders on all tree levels in the project panel. This way I, as a user, can start navigating down the tree again form a "clean slate".

### Additional information
WebStorm (and other Jetbrains IDEs) have a caret pointing up to close all folders and a caret pointing down to unfold all folders.

**Comment by JosephTLyons** [comment] 2023-05-15 19:10
Here's a couple of related issues:

- https://github.com/zed-industries/community/issues/158 - same request as  yours, but yours sounds like it might be more UI-driven.
- https://github.com/zed-industries/community/issues/800 - a setting to disable auto revealing the project panel

**Comment by Otterpocket** [comment] 2023-05-22 16:40
While I share the desire to have this feature, it would be even better if there were smarter functionality in place to prevent the proliferation of redundant open directories. For example, an auto-closing mechanism that automatically closes directories with no files open when closing a tab in the editor. This would help avoid potential issues and reduce the clutter caused by unnecessary directories. I think that it would enhance the overall user experience by allowing users to focus on what we are actually looking for without being obscured by numerous open but irrelevant directories.

**Comment by alvvaro** [comment] 2023-05-31 18:04
Some tree view widgets make it so alt-clicking the folder expands/collapses all children.

This behavior is native to macOS – you can try it out on the bookmark sidebar on Safari.

On VS Code this works when collapsing but not when expanding. I guess one might not want to accidentally expand the full contents of `node_modules`.

**Comment by JosephTLyons** [comment] 2023-08-18 12:58
This feature landed in a Zed a few versions ago.  When the project panel is in focus, there should be a `project panel: collapse all entries` command palette action.  It works by recursivley folding any directories open in projects, but it leaves the outermost projects unfolded, which would be similar to how other editors (that only allow one project open at at a time) work.

**Closed by JosephTLyons** 2023-08-18 12:58 UTC
Labels: enhancement, project panel
